/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package br.lp3tvc2.app;

import br.lp3tvc2.db.ProdutoDAO;
import br.lp3tvc2.entity.ProdutoFilial;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import org.apache.derby.impl.tools.sysinfo.Main;

/**
 *
 * @author curso
 */
public class ListaDeProdutos extends javax.swing.JFrame {

    /**
     * Creates new form ListaDeProdutos
     */
    public ListaDeProdutos() {
        initComponents();
        atualizarTabelaProdutoTotalFilial();

    }

    public void atualizarTabelaProdutoTotalFilial() {
        tableProdutoTotalFilial.clearSelection();
        tableProdutoTotalFilial.removeAll();

        DefaultTableModel tm = (DefaultTableModel) tableProdutoTotalFilial.getModel();
        tm.getDataVector().removeAllElements();

        List<ProdutoFilial> produtosFilialTotal = null;
        try {
            produtosFilialTotal = new ProdutoDAO().findProdutoETotalEmFiliais();
        } catch (Exception ex) {
            Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null, ex.getMessage(), "Erro ao atualizar tabela", JOptionPane.ERROR_MESSAGE);
        }

        for (ProdutoFilial produtosFilialTotalItem : produtosFilialTotal) {
            tm.addRow(new Object[]{
                produtosFilialTotalItem.getNomeProduto(),
                produtosFilialTotalItem.getTotalFilial()});
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tableProdutoTotalFilial = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        tableProdutoTotalFilial.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Produto", "Total em Todas Filiais"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tableProdutoTotalFilial);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(15, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(14, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tableProdutoTotalFilial;
    // End of variables declaration//GEN-END:variables
}
