/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package br.lp3tvc2.app;

/**
 *
 * @author curso
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
        setExtendedState(Principal.MAXIMIZED_BOTH);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        menuEstoque = new javax.swing.JMenu();
        menuItemProdutos = new javax.swing.JMenuItem();
        menuItemTransferirProduto = new javax.swing.JMenuItem();
        menuItemDistribuirEstoque = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        menuFilial = new javax.swing.JMenu();
        menuItemFecharFilial = new javax.swing.JMenuItem();
        menuSair = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        menuEstoque.setText("Estoque");

        menuItemProdutos.setText("Produtos");
        menuItemProdutos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemProdutosActionPerformed(evt);
            }
        });
        menuEstoque.add(menuItemProdutos);

        menuItemTransferirProduto.setText("Transferir Produto");
        menuItemTransferirProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemTransferirProdutoActionPerformed(evt);
            }
        });
        menuEstoque.add(menuItemTransferirProduto);

        menuItemDistribuirEstoque.setText("Distribuir Estoque");
        menuItemDistribuirEstoque.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemDistribuirEstoqueActionPerformed(evt);
            }
        });
        menuEstoque.add(menuItemDistribuirEstoque);

        jMenuItem1.setText("Lista Produto e Total em Filiais");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        menuEstoque.add(jMenuItem1);

        jMenuBar1.add(menuEstoque);

        menuFilial.setText("Filial");

        menuItemFecharFilial.setText("Fechar Filial");
        menuItemFecharFilial.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuItemFecharFilialMouseClicked(evt);
            }
        });
        menuItemFecharFilial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemFecharFilialActionPerformed(evt);
            }
        });
        menuFilial.add(menuItemFecharFilial);

        jMenuBar1.add(menuFilial);

        menuSair.setText("Sair");
        menuSair.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuSairMouseClicked(evt);
            }
        });
        jMenuBar1.add(menuSair);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 578, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 279, Short.MAX_VALUE)
        );

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-586)/2, (screenSize.height-334)/2, 586, 334);
    }// </editor-fold>//GEN-END:initComponents

    private void menuSairMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuSairMouseClicked
        this.dispose();
    }//GEN-LAST:event_menuSairMouseClicked

    private void menuItemFecharFilialMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuItemFecharFilialMouseClicked
        
    }//GEN-LAST:event_menuItemFecharFilialMouseClicked

    private void menuItemProdutosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemProdutosActionPerformed
        new ListaEstoque().setVisible(true);
    }//GEN-LAST:event_menuItemProdutosActionPerformed

    private void menuItemTransferirProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemTransferirProdutoActionPerformed
        new TransporteProduto().setVisible(true);
    }//GEN-LAST:event_menuItemTransferirProdutoActionPerformed

    private void menuItemFecharFilialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemFecharFilialActionPerformed
        new FecharFilial().setVisible(true);
    }//GEN-LAST:event_menuItemFecharFilialActionPerformed

    private void menuItemDistribuirEstoqueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemDistribuirEstoqueActionPerformed
        new DistribuirEstoque().setVisible(true);
    }//GEN-LAST:event_menuItemDistribuirEstoqueActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        new ListaDeProdutos().setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenu menuEstoque;
    private javax.swing.JMenu menuFilial;
    private javax.swing.JMenuItem menuItemDistribuirEstoque;
    private javax.swing.JMenuItem menuItemFecharFilial;
    private javax.swing.JMenuItem menuItemProdutos;
    private javax.swing.JMenuItem menuItemTransferirProduto;
    private javax.swing.JMenu menuSair;
    // End of variables declaration//GEN-END:variables
}
