/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package br.lp3tvc2.app;

import br.lp3tvc2.db.ProdutoDAO;
import br.lp3tvc2.entity.Estoque;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author tassio
 */
public class TransporteProduto extends javax.swing.JFrame {

    /**
     * Creates new form TransporteProduto
     */
    public TransporteProduto() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        textFieldFilialDe = new javax.swing.JTextField();
        labelFilialDe = new javax.swing.JLabel();
        labelFilialPara = new javax.swing.JLabel();
        textFieldFilialPara = new javax.swing.JTextField();
        labelProduto = new javax.swing.JLabel();
        textFieldProduto = new javax.swing.JTextField();
        buttonTransferir = new javax.swing.JButton();
        buttonCancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Transferencia de produto entre filiais");

        textFieldFilialDe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFieldFilialDeActionPerformed(evt);
            }
        });

        labelFilialDe.setText("Da filial:");

        labelFilialPara.setText("Para a filial:");

        labelProduto.setText("Transferir o produto:");

        buttonTransferir.setText("Transferir");
        buttonTransferir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonTransferirActionPerformed(evt);
            }
        });

        buttonCancelar.setText("Cancelar");
        buttonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(labelProduto)
                                .addGap(12, 12, 12)
                                .addComponent(textFieldProduto))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(labelFilialDe)
                                .addGap(18, 18, 18)
                                .addComponent(textFieldFilialDe, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(labelFilialPara)
                                .addGap(18, 18, 18)
                                .addComponent(textFieldFilialPara))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(buttonTransferir)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(buttonCancelar)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(labelProduto))
                    .addComponent(textFieldProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelFilialDe)
                    .addComponent(textFieldFilialDe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelFilialPara)
                    .addComponent(textFieldFilialPara, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonCancelar)
                    .addComponent(buttonTransferir))
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void textFieldFilialDeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFieldFilialDeActionPerformed
        this.dispose();
    }//GEN-LAST:event_textFieldFilialDeActionPerformed

    private void buttonTransferirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonTransferirActionPerformed
        String nomeProduto = textFieldProduto.getText();
        String nomeFilialDe = textFieldFilialDe.getText();
        String nomeFilialPara = textFieldFilialPara.getText();

        if (nomeProduto == null || nomeFilialDe == null || nomeFilialPara == null) {
            JOptionPane.showMessageDialog(null, "Por favor, preencha todos os campos", "Campos obrigatórios", JOptionPane.ERROR_MESSAGE);
            return;
        }
        try {
            new ProdutoDAO().begin();
            
            Estoque produtoFilialDe = new ProdutoDAO().findBYNomeAndFilial(nomeProduto, nomeFilialDe);
            Estoque produtoFilialPara = new ProdutoDAO().findBYNomeAndFilial(nomeProduto, nomeFilialPara);

            if (produtoFilialDe == null) {
                JOptionPane.showMessageDialog(null, "Não existe o produto "
                        + nomeProduto + " na filial " + nomeFilialDe + " !", "OPS!", JOptionPane.ERROR_MESSAGE);
                return;
            } else if (produtoFilialPara == null) {
                JOptionPane.showMessageDialog(null, "Não existe o produto "
                        + nomeProduto + " na filial " + nomeFilialDe + " !", "OPS!", JOptionPane.ERROR_MESSAGE);
                produtoFilialPara = new Estoque();
                produtoFilialPara.getEstoquePK().setProduto(produtoFilialDe.getEstoquePK().getProduto());
                produtoFilialPara.getEstoquePK().setFilial(nomeFilialPara);
                produtoFilialPara.setQuantidade(produtoFilialDe.getQuantidade());
                produtoFilialDe.setQuantidade(0);
                new ProdutoDAO().updateProduto(produtoFilialDe);
                new ProdutoDAO().insertProduto(produtoFilialPara);
            } else {
                produtoFilialPara.setQuantidade(produtoFilialPara.getQuantidade() + produtoFilialDe.getQuantidade());
                produtoFilialDe.setQuantidade(0);
                
                new ProdutoDAO().updateProduto(produtoFilialDe);
                new ProdutoDAO().updateProduto(produtoFilialPara);
            }

            new ProdutoDAO().commit();
            
            JOptionPane.showMessageDialog(null, "Transferência realizada", "Tranferência", JOptionPane.INFORMATION_MESSAGE);
            textFieldFilialDe.setText("");
            textFieldFilialPara.setText("");
            textFieldProduto.setText("");
        } catch (Exception ex) {
            try {
                new ProdutoDAO().rollback();
            } catch (Exception ex1) {
                Logger.getLogger(ListaEstoque.class.getName()).log(Level.SEVERE, null, ex1);
            }
            Logger.getLogger(TransporteProduto.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null, ex.getMessage(), "Erro ao tranferir", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_buttonTransferirActionPerformed

    private void buttonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCancelarActionPerformed
        this.dispose();
    }//GEN-LAST:event_buttonCancelarActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonCancelar;
    private javax.swing.JButton buttonTransferir;
    private javax.swing.JLabel labelFilialDe;
    private javax.swing.JLabel labelFilialPara;
    private javax.swing.JLabel labelProduto;
    private javax.swing.JTextField textFieldFilialDe;
    private javax.swing.JTextField textFieldFilialPara;
    private javax.swing.JTextField textFieldProduto;
    // End of variables declaration//GEN-END:variables
}
